[book]
title = "Fusion Blossom Tutorial"
description = ""
authors = ["Yue Wu"]
language = "en"

[rust]
edition = "2021"

[output.html]
mathjax-support = true
site-url = "/"
git-repository-url = "https://github.com/yuewuo/fusion-blossom"
# edit-url-template = "https://github.com/yuewuo/fusion-blossom/blob/dev/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
# "/format/config.html" = "configuration/index.html"

[build]
build-dir = "../tutorial-dist"

[preprocessor.bib]
bibliography = "ref.bib"
